// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TestML.Model
{
    public class ModelInput
    {
        [ColumnName("Lan"), LoadColumn(0)]
        public float Lan { get; set; }


        [ColumnName("Word"), LoadColumn(1)]
        public string Word { get; set; }


    }
}
